"""empty message

Revision ID: cd4fc1fd5257
Revises: ed92aa520c6c
Create Date: 2021-02-07 19:26:17.928913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4fc1fd5257'
down_revision = 'ed92aa520c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('age', sa.Float(), nullable=False),
    sa.Column('species', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['animal_center.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
